---
- name: Check if SWAP is enabled
  ansible.builtin.command: swapon --noheadings --show
  register: swap_status
  ignore_errors: true
  changed_when: false

- name: Disable SWAP since Kubernetes can't work with swap enabled (1/2)
  ansible.builtin.shell: swapoff -a
  when: swap_status.stdout != ""
  become: true
  changed_when: swap_status.stdout != ""

- name: Disable SWAP in fstab since Kubernetes can't work with swap enabled (2/2)
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'
  when: swap_status.stdout != ""
  become: true
